# Generated by Django 4.2.7 on 2023-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='message',
        ),
    ]
